batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition/202412101123/model.keras
train_epochs: 100
train_workers: 20
vocab: r/,s0Uxt#"JlyaHKjLEcVOh!pX&o*iGW:9qwC.MZ-N7'Ym?b+fQDP(Auk4Fd2v3Bz5)T6enIRS18;g
width: 128
